### ISSUE TITLE
Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by JohnnyTToxic** [metekamil/ATT-Uverse-Automated-Router-Rebooter#4]
Hey, I'm not good with node.js but can you help troubleshoot?

I have cloned repo, installed npm and nodejs from fresh install. When I attempt to run reboot.js on Node version v8.10.0 I get the following error:

/home/me/ATT-Uverse-Automated-Router-Rebooter/reboot.js:32
        var nonce=body.substr(body.indexOf("NONCE")).toLowerCase();
                       ^

TypeError: Cannot read property 'substr' of undefined
    at Request._callback (/home/odroid/ATT-Uverse-Automated-Router-Rebooter/reboot.js:32:24)
    at self.callback (/usr/lib/nodejs/request/index.js:148:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at ClientRequest.self.clientErrorHandler (/usr/lib/nodejs/request/index.js:258:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)

**Comment by metekamil** [comment]
@JohnnyTToxic I've added an error message which should help you resolve this issue.
